platform :ios, '14.0'

use_frameworks!
install! 'cocoapods',
         :deterministic_uuids => false,
         :disable_input_output_paths => true,
         :preserve_pod_file_structure => true

target 'BLEExtractorExample' do
  pod 'BLEExtractor', '~> 1.1.9'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Basic settings
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['SKIP_INSTALL'] = 'NO'
        
        # Code signing settings
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
        
        # Library and framework settings
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['VALIDATE_WORKSPACE'] = 'YES'
        
        # Sandbox and permission settings
        config.build_settings['ENABLE_APP_SANDBOX'] = 'NO'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        
        # Metal framework settings
        config.build_settings['ENABLE_METAL_API_VALIDATION'] = 'NO'
        config.build_settings['MTL_ENABLE_DEBUG_INFO'] = 'NO'
        
        # Add necessary capabilities
        config.build_settings['ENABLE_HARDENED_RUNTIME'] = 'NO'
        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
        config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = '$(PRODUCT_NAME)-Swift.h'
        
        # File system access
        config.build_settings['ENABLE_USER_SELECTED_FILES'] = 'readwrite'
        config.build_settings['ENABLE_DOWNLOADS_SANDBOX'] = 'NO'
        
        # Bluetooth specific settings
        config.build_settings['ENABLE_BLUETOOTH'] = 'YES'
        config.build_settings['BLUETOOTH_USAGE_DESCRIPTION'] = 'App needs Bluetooth access to scan and connect to BLE devices'
      end
    end
    
    # Enable necessary capabilities in the main app target
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PERMISSION_BLUETOOTH=1'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D PERMISSION_BLUETOOTH'
        end
      end
    end
  end
end
