name: Deploy to CocoaPods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  lint:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Get Version from Podspec
      id: get_version
      run: |
        VERSION=$(grep -m 1 "s.version.*=" BLEExtractor.podspec | grep -o '".*"' | sed 's/"//g')
        echo "Found version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    - name: Lint Podspec
      run: pod lib lint --allow-warnings
      
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build and Test
      run: |
        swift test --enable-test-discovery
          
  create-release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.check_release.outputs.create_release }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Check if release exists
      id: check_release
      run: |
        VERSION="${{ needs.lint.outputs.version }}"
        echo "Checking for version: $VERSION"
        if ! git ls-remote --tags origin | grep -q "refs/tags/$VERSION$"; then
          echo "create_release=true" >> $GITHUB_OUTPUT
          echo "Version $VERSION does not exist, will create release"
        else
          echo "Version $VERSION already exists, skipping release"
        fi
    
    - name: Create Release
      if: steps.check_release.outputs.create_release == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ needs.lint.outputs.version }}"
        release_name: "Version ${{ needs.lint.outputs.version }}"
        body: |
          Release version ${{ needs.lint.outputs.version }}
          
          Changes in this version:
          - Enhanced SwiftUI integration
          - Improved Bluetooth state handling
          - Bug fixes and performance improvements
        draft: false
        prerelease: false
          
  deploy:
    needs: [create-release, lint]
    runs-on: macos-latest
    if: needs.create-release.outputs.release_created == 'true'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        echo "Deploying version ${{ needs.lint.outputs.version }} to CocoaPods"
        pod trunk push --allow-warnings 