name: Deploy to CocoaPods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  lint:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Get Version from Podspec
      id: get_version
      shell: bash
      run: |
        VERSION=$(grep -m 1 "s.version.*=" BLEExtractor.podspec | grep -o '".*"' | sed 's/"//g')
        echo "Found version: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
    - name: Lint Podspec
      run: pod lib lint --allow-warnings
      
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build and Test
      run: |
        swift test --enable-test-discovery
          
  create-release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get current version
      id: version
      run: |
        echo "VERSION=${{ needs.lint.outputs.version }}" >> "$GITHUB_ENV"
        echo "Current version is ${{ needs.lint.outputs.version }}"
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ needs.lint.outputs.version }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Version ${{ env.VERSION }}
        body: |
          Release version ${{ env.VERSION }}
          
          Changes in this version:
          - Enhanced SwiftUI integration
          - Improved Bluetooth state handling
          - Bug fixes and performance improvements
        draft: false
        prerelease: false
          
  deploy:
    needs: [create-release, lint]
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        VERSION: ${{ needs.lint.outputs.version }}
      run: |
        echo "Deploying version $VERSION to CocoaPods"
        pod trunk push --allow-warnings 