name: Deploy to CocoaPods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Debug Directory
      run: |
        pwd
        ls -la
        
    - name: Get Version from Podspec
      id: get_version
      run: |
        echo "Current directory contents:"
        ls -la
        
        echo "Checking for podspec file..."
        PODSPEC_FILE="BLEExtractor.podspec"
        
        if [ ! -f "$PODSPEC_FILE" ]; then
          echo "::error::Podspec file not found at $(pwd)/$PODSPEC_FILE"
          exit 1
        fi
        
        echo "Reading podspec file..."
        echo "File contents:"
        cat "$PODSPEC_FILE"
        
        echo "Extracting version..."
        VERSION=$(grep -m 1 "s\.version\s*=" "$PODSPEC_FILE" | sed -E "s/.*version.*=\s*'(.*)'/\1/")
        
        if [ -z "$VERSION" ]; then
          echo "::error::Could not extract version from podspec"
          exit 1
        fi
        
        # Trim any whitespace
        VERSION=$(echo "$VERSION" | xargs)
        
        echo "Found version: '$VERSION'"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
  
  lint:
    needs: version
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Lint Podspec
      run: pod lib lint --allow-warnings
      
  test:
    needs: version
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build and Test
      run: |
        swift test --enable-test-discovery
          
  create-release:
    needs: [version, lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug Version
      run: |
        echo "Version to be released: ${{ needs.version.outputs.version }}"
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: Version ${{ needs.version.outputs.version }}
        body: |
          Release version ${{ needs.version.outputs.version }}
          
          Changes in this version:
          - Enhanced SwiftUI integration
          - Improved Bluetooth state handling
          - Bug fixes and performance improvements
        draft: false
        prerelease: false
          
  deploy:
    needs: [version, create-release]
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        echo "Deploying version ${{ needs.version.outputs.version }} to CocoaPods"
        pod trunk push --allow-warnings 